CREATE TABLE IF NOT EXISTS  {biao_type} (
  `id` int(2) NOT NULL AUTO_INCREMENT,
  `biao_type_name` varchar(16) NOT NULL,
  `available` int(1) NOT NULL,
  `password_model` int(1) NOT NULL,
  `happy_model` int(1) NOT NULL,
  `day_model` int(1) NOT NULL,
  `auto_verify` int(1) NOT NULL,
  `auto_full_verify` int(1) NOT NULL,
  `min_amount` int(11) NOT NULL,
  `max_amount` int(11) NOT NULL,
  `min_interest_rate` decimal(5,4) NOT NULL,
  `max_interest_rate` decimal(5,4) NOT NULL,
  `advance_time` int(2) NOT NULL,
  `advance_scope` int(1) NOT NULL,
  `advance_vip_scope` int(1) NOT NULL,
  `late_interest_rate` decimal(5,4) NOT NULL,
  `borrow_fee_rate` decimal(5,4) NOT NULL,
  `interest_fee_rate` decimal(5,4) NOT NULL,
  `borrow_day_fee_rate` decimal(5,4) NOT NULL,
  `frost_rate` decimal(5,4) NOT NULL,
  `advance_rate` decimal(5,4) NOT NULL,
  `advance_vip_rate` decimal(5,4) NOT NULL,
  `late_customer_interest_rate` decimal(5,4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM;